2025-07-29 10:45:47,585 [INFO] [STARTUP] lidar_viewer.py started.
2025-07-29 10:45:47,986 [DEBUG] matplotlib data path: C:\Users\W0491597\AppData\Local\miniforge3\envs\lidarviewer312\Lib\site-packages\matplotlib\mpl-data
2025-07-29 10:45:47,994 [DEBUG] CONFIGDIR=C:\Users\W0491597\.matplotlib
2025-07-29 10:45:48,010 [DEBUG] interactive is False
2025-07-29 10:45:48,010 [DEBUG] platform is win32
2025-07-29 10:45:48,094 [DEBUG] CACHEDIR=C:\Users\W0491597\.matplotlib
2025-07-29 10:45:48,094 [DEBUG] Using fontManager instance from C:\Users\W0491597\.matplotlib\fontlist-v390.json
2025-08-07 12:43:45,740 - LidarViewer - INFO - Test info message
2025-08-07 12:43:45,740 - LidarViewer - WARNING - Test warning message
2025-08-07 12:43:45,740 - LidarViewer - ERROR - Test error message
2025-08-07 12:43:45,741 - LidarViewer - INFO - This info should be suppressed
2025-08-07 12:43:45,741 - LidarViewer - ERROR - This error should still appear
2025-08-07 12:43:45,753 - LidarViewer - ERROR - LidarViewerException: Failed to load layer: test_file.las - File not found (code: LAYER_LOAD_ERROR)
2025-08-07 12:43:45,753 - LidarViewer - ERROR - Error executing failing_function: Test error
2025-08-07 12:43:45,754 - LidarViewer - ERROR - Error in test operation: Test error
Traceback (most recent call last):
  File "c:\Users\W0491597\Documents\Arun\LidarViewer\test_quality_improvements.py", line 146, in test_error_handling
    raise ValueError("Test error")
ValueError: Test error
